name: Branch Deploy
on:
    repository_dispatch:
        types: branch-deploy

jobs:
    deploy:
        timeout-minutes: 30
        runs-on: self-hosted

        steps:
            - uses: actions/checkout@v2
              with:
                  ref: ${{ github.event.client_payload.ref }}
                  fetch-depth: 0

            - name: Set Node.JS 14.x
              uses: actions/setup-node@v2-beta
              with:
                  node-version: '14'

            - name: install yarn
              run: if ! yarn --version; then npm install -g yarn; fi

